### ISSUE TITLE
login fails...

### ISSUE THREAD

**Issue by edit4ever** [edit4ever/script.module.zap2xml#8]
zap2it website changes are causing login failures...

**Comment by Schmell** [comment]
i dont get a pop-up

**Comment by Schmell** [comment]
tvguide is working i think

**Comment by Schmell** [comment]
the script looks fine. That pop up was always there. Its just that when you use the login the response is not one of success.

> Oops...

We're sorry. Something went wrong.
Please try again in a moment.
or

> Invalid e-mail address/password. Please log in again.

this is weird because i am already logged in according to the header which says Welcome, schmell
if i just go to http://tvschedule.zap2it.com/ i can see my schedule with out logging in.
I will keep poking at this, but i think its something wrong with zap2it's script at this point

**Comment by Schmell** [comment]
maybe a feature of the script could be to check and see if you are already logged in before re-sending login info?? Not sure yet

**Comment by edit4ever** [comment]
Figured it out - the match for the login needed to be updated:

'._Logout of your Screener account._'

Updated the release - please download and test!
